### ISSUE TITLE
Notification not working

### ISSUE THREAD

**Issue by dtrodger** [jenschelkopf/issue-label-notification-action#14]
Here's my workflow. When I create / add a 'bug' label to an issue, the notification isn't sent. Any help would be awesome!!
<img width="733" alt="Screen Shot 2020-09-15 at 11 52 38 AM" src="https://user-images.githubusercontent.com/16841791/93240742-1e869b00-f74a-11ea-81e8-3af6710deb7b.png">

**Comment by dtrodger** [comment]
<img width="1019" alt="Screen Shot 2020-09-15 at 12 00 13 PM" src="https://user-images.githubusercontent.com/16841791/93241535-1418d100-f74b-11ea-864f-7586140e4895.png">

Here's the job logs.

**Comment by jenschelkopf** [comment]
Hi there - version 1.2 of this action requires that GITHUB_TOKEN be passed as an input in the workflow file. Here's a link to the [README](https://github.com/jenschelkopf/issue-label-notification-action/tree/1.2#example-workflow) for that version. 

Version 1.3 [removes this requirement](https://github.com/jenschelkopf/issue-label-notification-action/releases/tag/1.3). 

👉 To fix your job failures, change 1.2 to 1.3 in your workflow file.

I've also just updated the README in the master branch, which showed an incorrect example of 1.2. It now shows a correct 1.3 example.

**Comment by jenschelkopf** [comment]
I'm closing this issue as resolved, but please re-open if this does not solve your problem.

**Comment by dtrodger** [comment]
Switching to 1.3 solved it. Thanks for the quick reply!
