### ISSUE TITLE
Action does not fire if a bot labels the issue

### ISSUE THREAD

**Issue by BrianTJackett** [jenschelkopf/issue-label-notification-action#7]
I am working on a scenario that a GitHub action workflow will fire when issues are created.

**Not working - bot labels the issue**
If the issue contains specific text then an action will automatically add a label to the issue using the context of a bot.  In this scenario the issue label notification never fires.

Example
[https://github.com/BrianTJackett/issue-notification-workflow/issues/11](https://github.com/BrianTJackett/issue-notification-workflow/issues/11)

**Working - user labels the issue**
If I change the auto labeler to use a personal access token (PAT) the label is added as my own account and not a bot.  In this scenario the issue label notification does fire.

Example
[https://github.com/BrianTJackett/issue-notification-workflow/issues/12](https://github.com/BrianTJackett/issue-notification-workflow/issues/12)

Is there a reason why this action would not fire when a bot labels the issue?  Thanks for providing this community action and any help you can offer.

**Comment by jenschelkopf** [comment]
Hey @BrianTJackett, thanks for the issue. I'm not sure why the workflow wouldn't trigger when a bot adds a label. I'll take a look!

**Comment by jenschelkopf** [comment]
Hey @BrianTJackett, currently you cannot trigger new workflow runs using the GITHUB_TOKEN. This is documented here: https://help.github.com/en/actions/reference/events-that-trigger-workflows#webhook-events

Here's a screenshot:

![Screen Shot 2020-05-19 at 10 43 05 AM](https://user-images.githubusercontent.com/1865328/82347908-d46cf300-99bd-11ea-80a9-0fe009b4cb50.png)

I'm not sure why this is, and what you're doing certainly seems like a reasonable thing! I've opened an issue internally to see if we can get that changed. In the meantime, continue using the PAT.

**Comment by BrianTJackett** [comment]
Thanks for the background info. I'm ok with the workaround of using a PAT for the time being.  Closing this issue but if you do hear any updates feel free to re-open / post in here.
